# Generated by Django 4.0.3 on 2022-04-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
